// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxCccMn2wIwd5NmSOfqTUwBPfHXaujfLQ',
    appId: '1:558081366146:web:dd9c0c3086f54a541dfc9b',
    messagingSenderId: '558081366146',
    projectId: 'homeworkoutapp-c8b67',
    authDomain: 'homeworkoutapp-c8b67.firebaseapp.com',
    storageBucket: 'homeworkoutapp-c8b67.firebasestorage.app',
    measurementId: 'G-KQRMKMRVPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6McJ1JE88wJddsfczS046aEQrlK6yh7c',
    appId: '1:558081366146:android:7aa8be1fdf0ab2241dfc9b',
    messagingSenderId: '558081366146',
    projectId: 'homeworkoutapp-c8b67',
    storageBucket: 'homeworkoutapp-c8b67.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxCccMn2wIwd5NmSOfqTUwBPfHXaujfLQ',
    appId: '1:558081366146:web:3eb1240883be7b521dfc9b',
    messagingSenderId: '558081366146',
    projectId: 'homeworkoutapp-c8b67',
    authDomain: 'homeworkoutapp-c8b67.firebaseapp.com',
    storageBucket: 'homeworkoutapp-c8b67.firebasestorage.app',
    measurementId: 'G-XBG5FN2L07',
  );
}
